Sseom/Smssme

Smssme.xcodeproj/project.pbxproj
Smssme/SceneDelegate.swift
Smssme/View/UIComponentFactory.swift

https://github.com/Sseom/Smssme/issues/1

1 feat/ #1 UIComponent - LabelFactory

---

Smssme.xcodeproj/project.pbxproj
Smssme/Controller/FinancialPlanCreateVC.swift
Smssme/Controller/FinancialPlanSelectionVC.swift
Smssme/Controller/Login/LoginVC.swift
Smssme/SceneDelegate.swift
Smssme/View/FinancialPlanCell.swift
Smssme/View/FinancialPlanCreateView.swift
Smssme/View/FinancialPlanSelectView.swift
Smssme/View/Login/LoginView.swift

- 로그인 UI 틀만 잡아 놨습니다. 
- 혜정님 컴포넌트 적용 예정
- 기능 추가 예정입니다.
close: #7

Feat/#7 login UI

---

Smssme.xcodeproj/project.pbxproj
Smssme/Common/Model.swift
Smssme/Controller/Login/LoginVC.swift
Smssme/Controller/TabBarController.swift
Smssme/SceneDelegate.swift
Smssme/View/Login/LoginView.swift

하단 네번째 탭바에 로그인 뷰 임시 추가 

---

Smssme.xcodeproj/project.pbxproj
Smssme/Controller/MainPage/MainPageVC.swift
Smssme/Controller/TabBarController.swift
Smssme/Model/TodayFinancia.swift
Smssme/View/MainPage/MainPageView.swift

[feat] 메인페이지 UI 추가

---

Smssme.xcodeproj/project.pbxproj
Smssme/Controller/MoneyDiary/DailyTransaction/DailyTransactionCell.swift
Smssme/Controller/MoneyDiary/DailyTransaction/DailyTransactionView.swift
Smssme/Controller/MoneyDiary/MoneyDiaryCalendarCell.swift
Smssme/Controller/MoneyDiary/MoneyDiaryCalendarView.swift
Smssme/View/MoneyDiary/DailyTransaction/DailyTransactionVC.swift
Smssme/View/MoneyDiary/MoneyDiaryVC.swift

당일거래 리스트뷰 컬렉션뷰로 구성 -> 구성 완료
리유저블 셀 내부 구현 -> 구현완료 
하프모달로 구현-> 구현완료 
close #9

Feat/#9-캘린더 셀 터치시 하프모달 전환 및 내부 레이블, 셀 구현

---

Smssme.xcodeproj/project.pbxproj
Smssme/Model/CoreData/Assets/Assets+CoreDataClass.swift
Smssme/Model/CoreData/Assets/Assets+CoreDataProperties.swift
Smssme/Model/CoreData/Assets/AssetsCoreDataManager.swift
Smssme/Model/CoreData/Budget/Budget+CoreDataClass.swift
Smssme/Model/CoreData/Budget/Budget+CoreDataProperties.swift
Smssme/Model/CoreData/Budget/BudgetCoreDataManager.swift
Smssme/Model/CoreData/Diary/Diary+CoreDataClass.swift
Smssme/Model/CoreData/Diary/Diary+CoreDataProperties.swift
Smssme/Model/CoreData/Diary/DiaryCoreDataManager.swift
Smssme/Model/CoreData/Goal/Goal+CoreDataClass.swift
Smssme/Model/CoreData/Goal/Goal+CoreDataProperties.swift
Smssme/Model/CoreData/Goal/GoalCoreDataManager.swift
Smssme/Model/CoreData/User/User+CoreDataClass.swift
Smssme/Model/CoreData/User/User+CoreDataProperties.swift
Smssme/Model/CoreData/User/UserCoreDataManager.swift
Smssme/Smssme.xcdatamodeld/Smssme.xcdatamodel/contents

- 코어데이터 엔티티 추가
- DataManager는 파일만 넣어놓고 구현은 안했습니다.

[etc] CoreData Entity, DataManager 추가

---

Smssme.xcodeproj/project.pbxproj
Smssme/Controller/MoneyDiary/MoneyDiaryEditView.swift
Smssme/Controller/TabBarController.swift
Smssme/View/MoneyDiary/MoneyDiaryEditVC.swift

- 머니다이어리 수입지출 내역편집 UI
- 스택뷰를 써서 UI가 좀 빡빡하게 잡혀있습니다. 나중에 좋은 방안을 생각해보겠습니다.
|타이틀1|타이틀2|
|:---:|:---:|
|![image](https://github.com/user-attachments/assets/db5ac7e1-5559-404d-9850-2f9b12b65461)|![image](https://github.com/user-attachments/assets/db5ac7e1-5559-404d-9850-2f9b12b65461)

Feature/#35 money diary edit UI

---

Smssme.xcodeproj/project.pbxproj
Smssme/Controller/FinancialPlan/FinancialPlanConfirmVC.swift
Smssme/Controller/FinancialPlan/FinancialPlanCreateVC.swift
Smssme/Controller/FinancialPlan/FinancialPlanCurrentPlanVC.swift
Smssme/Controller/FinancialPlan/FinancialPlanSelectionVC.swift
Smssme/Controller/TabBarController.swift
Smssme/SceneDelegate.swift
Smssme/View/FinancialPlan/FinancialPlanCell.swift
Smssme/View/FinancialPlan/FinancialPlanConfirmView.swift
Smssme/View/FinancialPlan/FinancialPlanCreateView.swift
Smssme/View/FinancialPlan/FinancialPlanCurrentPlanCell.swift
Smssme/View/FinancialPlan/FinancialPlanCurrentPlanView.swift
Smssme/View/FinancialPlan/FinancialPlanSelectView.swift
Smssme/View/FinancialPlan/PlanCustomTextField.swift

막대그래프 레이아웃 박살나는거 고쳤습니다
컬렉션뷰로 변경

Feature/#43 financial plan/current page UI 

---

Smssme/View/Util/UIColorSet.swift

중복되는 코드가 있어서 삭제했습니다. 
(protocol cellReuseable)
- 본 PR에는 어떤 구현사항이 있나요?
- 정리헤서 작성해주세요
- 앞으로 개선할 계획이 있다면 작성해주세요. 없으면 지워주세요!
|타이틀1|타이틀2|
|:---:|:---:|
|<img src="이미지링크" width="400">|<img src="이미지링크" width="400">

HotFix/ 중복된 코드 삭제 (Update UIColorSet).swift

---

Smssme/Controller/FinancialPlan/FinancialPlanSelectionVC.swift
Smssme/Smssme.xcdatamodeld/Smssme.xcdatamodel/contents

[etc] coreData relationship설정 id통일

---

Smssme/View/MoneyDiary/DailyTransaction/DailyTransactionVC.swift
Smssme/View/MoneyDiary/MoneyDiaryVC.swift
Smssme/View/Util/DateManager.swift

- 본 PR에는 어떤 구현사항이 있나요?
- 정리헤서 작성해주세요
- 앞으로 개선할 계획이 있다면 작성해주세요. 없으면 지워주세요!
|타이틀1|타이틀2|
|:---:|:---:|
|<img src="이미지링크" width="400">|<img src="이미지링크" width="400">

feat/ 뷰 연결하기

---

Smssme.xcodeproj/project.pbxproj
Smssme/Controller/Login/LoginVC.swift
Smssme/Controller/Mypage/MypageVC.swift
Smssme/Controller/Mypage/TestTableViewCell.swift
Smssme/Controller/Mypage/TestTableViewController.swift
Smssme/SceneDelegate.swift
Smssme/View/Mypage/MypageView.swift
Smssme/View/Mypage/MypageViewCell.swift

- 마이페이지 전체적인 UI 수정 작업 테이블뷰로 진행되었습니다.
- 로그아웃, 회원탈퇴, 개인정보처리방침 셀 클릭 시 기능 구현됩니다.
close: #76, #39
- 현재 내 정보 관리, 알림 설정 부분은 추가 기능 구현 중입니다. 
- 핑크색으로 표시해둔 부분이 사용자의 프로필을 나타내는 부분인데 어떻게 좀 더 수정 보완하면 좋을지 의견 궁금합니다. 
- 사용자 로그인 상태에 따른 프로필 닉네임 수정 기능
- 내정보 수정 기능
- 각 섹션 별 하단에 구분 선이 있는데 위치 수정이 돼야할 것 같습니다. 
|타이틀1|타이틀2|
|:---:|:---:|
|![image](https://github.com/user-attachments/assets/bd68312c-a41a-4e96-b6bb-79f77f626032)|

마이페이지 UI 작업 수정 

---

Smssme/Controller/MoneyDiary/DailyTransaction/DailyTransactionVC.swift
Smssme/Controller/MoneyDiary/MoneyDiaryEditVC.swift
Smssme/Controller/MoneyDiary/MoneyDiaryVC.swift
Smssme/View/MoneyDiary/DailyTransaction/DailyTransactionCell.swift
Smssme/View/MoneyDiary/MoneyDiaryView.swift

[Feat / 내용수정기능 완료 / 당일 거래내역 조회가능]

Feat / 내용수정기능 완료 / 당일 거래내역 조회가능

---

Smssme/Controller/MoneyDiary/MoneyDiaryVC.swift

[ref] 예산안 VC 초기화 버그 수정

---

Smssme/Controller/Login/LoginVC.swift
Smssme/Controller/Login/SignUpVC.swift
Smssme/Controller/MainPage/MainPageVC.swift
Smssme/Controller/Mypage/MypageVC.swift
Smssme/View/Login/LoginView.swift
Smssme/View/Login/SignUpView.swift
Smssme/View/MainPage/MainPageView.swift

- 생년월일 기존 텍스트뷰에서 피커뷰로 수정
- 로그인 유무에 따른 메인페이지 welcomeTitle 변경
- 로그인/회원가입에서 잘못된 형식 입력 시에러 메시지 알럿 추가
- 성별 선택 파이어베이스에 저장 완료
- 비밀번호 일치 여부 추가

[feat]: 생년월일 피커뷰로 수정/ 메인페이지 로그인 유무에 따른 welcomeTitle 변경

---

Smssme/Controller/MoneyDiary/MoneyDiaryVC.swift
Smssme/Model/DateModel.swift
Smssme/View/MoneyDiary/MoneyDiaryCalendarCell.swift
Smssme/View/MoneyDiary/MoneyDiaryCalendarView.swift
Smssme/View/MoneyDiary/MoneyDiaryView.swift
Smssme/View/Util/DateManager.swift

캘린더 셀 이전달.익달 블러처리 
01 -> 1로 변환  (정규표현식 사용 )
다크모드 시 하얗게 통일 
세그먼트 색처리 
버튼 색과 배경설정 
- 앞으로 개선할 계획이 있다면 작성해주세요. 없으면 지워주세요!
|:---:|:---:|
|<img src="이미지링크" width="400">|<img src="이미지링크" width="400">

feat: 로직 일부수정 다크모드 대처

---

.gitignore

gitignore 트라이트라이
gitIgnore수정
만일 해결되지 않을 시 차선책으로는 리셋패키지를 자동화하는 법이라도..

[etc] Missing package product 의존성 문제 해결

---

Smssme/Controller/FinancialPlan/FinancialPlanCreationVC.swift
Smssme/Controller/FinancialPlan/FinancialPlanEditPlanVC.swift
Smssme/Controller/MoneyDiary/AutomaticTransactionVC.swift
Smssme/Model/CoreData/Budget/BudgetCoreDataManager.swift
Smssme/View/FinancialPlan/FinancialPlanCreationView.swift

- 이번 달 모아야 하는 금액/ 기한수정으로 음수 결과값일 시 0원
- 플랜 수정페이지 타이틀 표시
- 지현님 pr분까지 컨플릭해결

bug/이번달 모아야되는 금액 로직변경, 컨플릭 해결

---

Smssme/Controller/Assets/AssetsListVC.swift
Smssme/Controller/MainPage/MainPageVC.swift
Smssme/View/Util/ChartDataManager.swift

- 자산 안에 플랜 데이터 모은 금액으로 표시
- 마이너스 데이터는 9월 21일 이후로 진행

Fix/자산 안에 플랜 데이터 모은 금액으로 표시

---

Smssme.xcodeproj/project.pbxproj

Revert "pulled dev after commit"

---

Smssme.xcodeproj/project.pbxproj
Smssme/Scenes/FutureGraph/Controller/FutureGraphVC.swift
Smssme/Scenes/FutureGraph/View/FutureGraphCell.swift
Smssme/Scenes/FutureGraph/View/FutureGraphView.swift

- 미래 예상 자산 그래프
- 현재 내 자산을 가져오는 그래프는 추후 작업 예정
|차트|표|
|:---:|:---:|
|![image](https://github.com/user-attachments/assets/d686e4e1-b8dd-47ab-a223-ba845cd3e207)|![image](https://github.com/user-attachments/assets/9a4499d7-42f6-4b85-8ed1-820c999aac16)

[feat] 미래 예상 자산 그래프

---

Smssme.xcodeproj/project.pbxproj
Smssme/Scenes/MoneyDiary/Controller/MoneyDiaryVC.swift
Smssme/Scenes/MoneyDiary/View/MoneyDiaryCalendarCell.swift

지금 화면색상이 적용되는 시점에 대한 문제가 있어요
dev분기와 너무 멀어지기전에 PR하기위해 커밋푸시합니다.
- 본 PR에는 어떤 구현사항이 있나요?
- 정리헤서 작성해주세요
- 앞으로 개선할 계획이 있다면 작성해주세요. 없으면 지워주세요!
|타이틀1|타이틀2|
|:---:|:---:|
|<img src="이미지링크" width="400">|<img src="이미지링크" width="400">

feat : 신호등 기능 추가

---

Smssme/Scenes/Assets/View/AssetsEditView.swift
Smssme/Scenes/FutureGraph/Controller/FutureGraphVC.swift
Smssme/Scenes/FutureGraph/View/FutureGraphView.swift
Smssme/Scenes/MoneyDiary/Controller/MoneyDiaryBudgetEditVC.swift

- 미래 예상 자산 그래프 데이터 표출 방식 수정
- 그래프 애니메이션 적용
- 자산 편집 뷰 디자인 수정
|그래프|자산편집|
|:---:|:---:|
|![image](https://github.com/user-attachments/assets/6a07b1e2-7e51-4575-b751-5bc23fa57034)|![image](https://github.com/user-attachments/assets/ac0b6477-748a-471f-a2ac-de17f54e6529)

[feat] 미래 예상 자산 그래프 데이터 표출 방식 수정, 그래프 애니메이션 적용, 자산 편집 뷰 디자인 수정

---

Smssme/Scenes/MainPage/Controller/MainPageVC.swift
Smssme/Scenes/MainPage/View/MainPageView.swift

[fix] 메인 페이지 차트 문구 변경

---

Smssme/Common/UI/UILabelFactory.swift
Smssme/Model/CoreData/FinancialPlan/FinancialPlanService.swift
Smssme/Scenes/Authentication/Login/Controller/LoginVC.swift
Smssme/Scenes/FinancialPlan/Controller/CompleteModalVC.swift
Smssme/Scenes/FinancialPlan/Controller/FinancialPlanConfirmVC.swift
Smssme/Scenes/FinancialPlan/Controller/FinancialPlanCreationVC.swift
Smssme/Scenes/FinancialPlan/Controller/FinancialPlanCurrentPlanVC.swift
Smssme/Scenes/FinancialPlan/View/FinancialPlanCell.swift
Smssme/Scenes/FinancialPlan/View/FinancialPlanCreationView.swift

Feature/#213 tool tip 중간완성

---

Smssme.xcodeproj/project.pbxproj
Smssme/Model/CoreData/Budget/BudgetCoreDataManager.swift
Smssme/Scenes/FinancialPlan/View/FinancialPlanConfirmView.swift

[hotFix] 이번달 로직 수정

---

.gitignore
Smssme.xcodeproj/project.pbxproj

Reverts Sseom/Smssme#221
dev가 안열리는 이슈로 인해서 revert 진행합니다.

Revert "etc/깃이그노어에 추가한 xcconig 및 plist 파일이 추적되는 문제 "

---

Smssme/Notification/NotificationManager.swift
Smssme/Scenes/Authentication/Login/Controller/LoginVC.swift
Smssme/Scenes/Authentication/Mypage/Controller/MypageVC.swift
Smssme/Scenes/MainPage/Controller/MainPageVC.swift
Smssme/Scenes/MainPage/Controller/View/MainPageView.swift

[hotfix] 1.3.3 버전 배포 중 비회원 로그인 시 마이페이지에서 앱 꺼지는 문제 발생

---

Smssme/Notification/NotificationManager.swift
Smssme/Scenes/Authentication/SignUp/View/EditUserInfoView.swift
Smssme/Scenes/FutureGraph/Controller/FutureGraphVC.swift
Smssme/Scenes/FutureGraph/View/FutureGraphFirstView.swift
Smssme/Scenes/FutureGraph/View/FutureGraphSecondView.swift
Smssme/Scenes/Root/Controller/TabBarController.swift

- 매일 오후 9시 알림 기능 추가 
- 앱 심사 거절된 차트 및 마이페이지 아이패드용 탭바 UI 위치 수정

알림 기능 추가 및 심사 거절 요소 해결
